#ifndef MYCPU_PLATFORM_MMIO_H
#define MYCPU_PLATFORM_MMIO_H

#define MEM_BASE 0x80000000
#define MEM_SIZE (128 * 1024 * 1024)

#define UART_BASE 0x10000000
#define UART_SIZE 0x8
#define UART_REG_THR 0x0
#define UART_REG_IER 0x1
#define UART_REG_IIR 0x2
#define UART_REG_LSR 0x5
#define UART_IER_THRI 0x2

#define STORAGE_BASE 0x10001000
#define STORAGE_SIZE 0x400
#define STORAGE_MMIO_MAGIC 0x4d4d424c4b444556
#define STORAGE_MMIO_VERSION 0x1
#define STORAGE_BLOCK_SIZE 512
#define STORAGE_MAX_BLOCK_COUNT 1
#define STORAGE_REG_MAGIC 0x00
#define STORAGE_REG_VERSION 0x08
#define STORAGE_REG_BLOCK_SIZE 0x10
#define STORAGE_REG_CAPACITY_BLOCKS 0x18
#define STORAGE_REG_STATUS 0x20
#define STORAGE_REG_COMMAND 0x28
#define STORAGE_REG_LBA 0x30
#define STORAGE_REG_BLOCK_COUNT 0x38
#define STORAGE_REG_ERROR 0x40
#define STORAGE_DATA_WINDOW_OFFSET 0x80
#define STORAGE_DATA_WINDOW_SIZE (STORAGE_BLOCK_SIZE * STORAGE_MAX_BLOCK_COUNT)
#define STORAGE_STATUS_ATTACHED 0x1
#define STORAGE_STATUS_READY 0x2
#define STORAGE_STATUS_ERROR 0x4
#define STORAGE_CMD_NONE 0x0
#define STORAGE_CMD_READ 0x1
#define STORAGE_CMD_WRITE 0x2
#define STORAGE_ERR_NONE 0x0
#define STORAGE_ERR_NO_MEDIA 0x1
#define STORAGE_ERR_BAD_COMMAND 0x2
#define STORAGE_ERR_BAD_BLOCK_COUNT 0x3
#define STORAGE_ERR_LBA_RANGE 0x4

#define CLINT_BASE 0x02000000
#define CLINT_SIZE 0x10000

#define PLIC_BASE 0x0c000000
#define PLIC_SIZE 0x300000
#define PLIC_CONTEXT_MACHINE 0
#define PLIC_CONTEXT_SUPERVISOR 1
#define PLIC_SOURCE_UART_THRE 1
#define PLIC_PRIORITY_OFFSET(source_id) ((source_id) * 4)
#define PLIC_PENDING_OFFSET 0x1000
#define PLIC_ENABLE_OFFSET(context) (0x2000 + ((context) * 0x80))
#define PLIC_CONTEXT_OFFSET(context) (0x200000 + ((context) * 0x1000))
#define PLIC_THRESHOLD_OFFSET(context) PLIC_CONTEXT_OFFSET(context)
#define PLIC_CLAIM_OFFSET(context) (PLIC_CONTEXT_OFFSET(context) + 4)

#endif
