LINUX_PROTO_EXTERNAL_DIR ?= external/linux-riscv
LINUX_PROTO_IMAGE ?= $(LINUX_PROTO_EXTERNAL_DIR)/arch/riscv/boot/Image
LINUX_PROTO_DTB ?= $(LINUX_PROTO_EXTERNAL_DIR)/mycpu_virt.dtb
LINUX_PROTO_INITRD ?= $(LINUX_PROTO_EXTERNAL_DIR)/rootfs.cpio

WORKLOAD_IMAGE := $(LINUX_PROTO_IMAGE)
WORKLOAD_IMAGE_FORMAT := flat
WORKLOAD_LOAD_ADDR := $(BOARD_LINUX_KERNEL_ADDR)
WORKLOAD_BOOT_PROTOCOL := linux
WORKLOAD_DTB_IMAGE := $(LINUX_PROTO_DTB)
WORKLOAD_INITRD_IMAGE := $(LINUX_PROTO_INITRD)
WORKLOAD_PROBE_CYCLES := 5000
WORKLOAD_BUILD_COMMAND = :
WORKLOAD_CLEAN_COMMAND = :
