LINUX_PROTO_EXTERNAL_DIR ?= external/linux-riscv
LINUX_PROTO_IMAGE ?= $(LINUX_PROTO_EXTERNAL_DIR)/arch/riscv/boot/Image
LINUX_PROTO_SHIM_ELF := workloads/linux_proto/linux_sbi_shim.elf
LINUX_PROTO_SHIM_BIN := workloads/linux_proto/linux_sbi_shim.bin
LINUX_PROTO_MININIT_ELF := workloads/linux_proto/linux_mininit.elf
LINUX_PROTO_GENERATED_INITRD := workloads/linux_proto/rootfs.cpio
LINUX_PROTO_GENERATED_DISK := workloads/linux_proto/rootfs.ext4
LINUX_PROTO_GENERATED_DTS := workloads/linux_proto/mycpu_virt.dts
LINUX_PROTO_GENERATED_DTB := workloads/linux_proto/mycpu_virt.dtb
LINUX_PROTO_DTB ?= $(LINUX_PROTO_GENERATED_DTB)
LINUX_PROTO_EXTERNAL_INITRD := $(LINUX_PROTO_EXTERNAL_DIR)/rootfs.cpio
LINUX_PROTO_EXTERNAL_DISK := $(LINUX_PROTO_EXTERNAL_DIR)/rootfs.ext4
LINUX_PROTO_ROOTFS_MODE ?= initrd
LINUX_PROTO_BLOCK_BOOTARGS := console=ttyS0,115200 earlycon=ns16550a,mmio,0x10000000 root=/dev/vda rw rootfstype=ext4 rootwait init=/init loglevel=8 ignore_loglevel
LINUX_PROTO_DISK ?=

ifeq ($(LINUX_PROTO_ROOTFS_MODE),block)
LINUX_PROTO_DEFAULT_BOOTARGS := $(LINUX_PROTO_BLOCK_BOOTARGS)
else ifeq ($(LINUX_PROTO_ROOTFS_MODE),initrd)
LINUX_PROTO_DEFAULT_BOOTARGS := $(BOARD_LINUX_BOOTARGS)
else
$(error unsupported LINUX_PROTO_ROOTFS_MODE: $(LINUX_PROTO_ROOTFS_MODE))
endif

LINUX_PROTO_BOOTARGS ?= $(LINUX_PROTO_DEFAULT_BOOTARGS)
BOARD_LINUX_BOOTARGS := $(LINUX_PROTO_BOOTARGS)

ifeq ($(wildcard $(LINUX_PROTO_EXTERNAL_INITRD)),)
LINUX_PROTO_INITRD ?= $(LINUX_PROTO_GENERATED_INITRD)
else
LINUX_PROTO_INITRD ?= $(LINUX_PROTO_EXTERNAL_INITRD)
endif

ifeq ($(LINUX_PROTO_ROOTFS_MODE),block)
ifneq ($(strip $(LINUX_PROTO_DISK)),)
LINUX_PROTO_EFFECTIVE_DISK := $(LINUX_PROTO_DISK)
else ifneq ($(wildcard $(LINUX_PROTO_EXTERNAL_DISK)),)
LINUX_PROTO_EFFECTIVE_DISK := $(LINUX_PROTO_EXTERNAL_DISK)
else
LINUX_PROTO_EFFECTIVE_DISK := $(LINUX_PROTO_GENERATED_DISK)
endif
WORKLOAD_DISK ?= $(LINUX_PROTO_EFFECTIVE_DISK)
else ifneq ($(strip $(LINUX_PROTO_DISK)),)
WORKLOAD_DISK ?= $(LINUX_PROTO_DISK)
endif

WORKLOAD_IMAGE := $(LINUX_PROTO_SHIM_BIN)
WORKLOAD_IMAGE_FORMAT := flat
WORKLOAD_LOAD_ADDR := $(BOARD_RAM_BASE)
WORKLOAD_BOOT_PROTOCOL := linux
WORKLOAD_DTB_IMAGE := $(LINUX_PROTO_DTB)
ifeq ($(LINUX_PROTO_ROOTFS_MODE),block)
WORKLOAD_INITRD_IMAGE :=
else
WORKLOAD_INITRD_IMAGE := $(LINUX_PROTO_INITRD)
endif
WORKLOAD_PAYLOAD_ARGS += --payload $(LINUX_PROTO_IMAGE) $(BOARD_LINUX_KERNEL_ADDR)
WORKLOAD_GPR_SEED_ARGS += --set-reg a2 $(BOARD_LINUX_KERNEL_ADDR)
WORKLOAD_PROBE_CYCLES := 5000
LINUX_PROTO_BUILD_ARTIFACTS := $(LINUX_PROTO_SHIM_BIN)
ifeq ($(LINUX_PROTO_ROOTFS_MODE),block)
ifeq ($(strip $(WORKLOAD_DISK)),$(LINUX_PROTO_GENERATED_DISK))
LINUX_PROTO_BUILD_ARTIFACTS += $(LINUX_PROTO_GENERATED_DISK)
endif
else
ifeq ($(LINUX_PROTO_INITRD),$(LINUX_PROTO_GENERATED_INITRD))
LINUX_PROTO_BUILD_ARTIFACTS += $(LINUX_PROTO_GENERATED_INITRD)
endif
endif
ifeq ($(LINUX_PROTO_DTB),$(LINUX_PROTO_GENERATED_DTB))
LINUX_PROTO_BUILD_ARTIFACTS += $(LINUX_PROTO_GENERATED_DTB)
endif
WORKLOAD_BUILD_COMMAND = $(MAKE) $(LINUX_PROTO_BUILD_ARTIFACTS)
WORKLOAD_CLEAN_COMMAND = :
