LINUX_PROTO_EXTERNAL_DIR ?= external/linux-riscv
LINUX_PROTO_IMAGE ?= $(LINUX_PROTO_EXTERNAL_DIR)/arch/riscv/boot/Image
LINUX_PROTO_INITRD ?= $(LINUX_PROTO_EXTERNAL_DIR)/rootfs.cpio
LINUX_PROTO_SHIM_ELF := workloads/linux_proto/linux_sbi_shim.elf
LINUX_PROTO_SHIM_BIN := workloads/linux_proto/linux_sbi_shim.bin
LINUX_PROTO_GENERATED_DTS := workloads/linux_proto/mycpu_virt.dts
LINUX_PROTO_GENERATED_DTB := workloads/linux_proto/mycpu_virt.dtb
LINUX_PROTO_DTB ?= $(LINUX_PROTO_GENERATED_DTB)

WORKLOAD_IMAGE := $(LINUX_PROTO_SHIM_BIN)
WORKLOAD_IMAGE_FORMAT := flat
WORKLOAD_LOAD_ADDR := $(BOARD_RAM_BASE)
WORKLOAD_BOOT_PROTOCOL := linux
WORKLOAD_DTB_IMAGE := $(LINUX_PROTO_DTB)
WORKLOAD_INITRD_IMAGE := $(LINUX_PROTO_INITRD)
WORKLOAD_PAYLOAD_ARGS += --payload $(LINUX_PROTO_IMAGE) $(BOARD_LINUX_KERNEL_ADDR)
WORKLOAD_GPR_SEED_ARGS += --set-reg a2 $(BOARD_LINUX_KERNEL_ADDR)
WORKLOAD_PROBE_CYCLES := 5000
ifeq ($(LINUX_PROTO_DTB),$(LINUX_PROTO_GENERATED_DTB))
WORKLOAD_BUILD_COMMAND = $(MAKE) $(LINUX_PROTO_SHIM_BIN) $(LINUX_PROTO_GENERATED_DTB)
else
WORKLOAD_BUILD_COMMAND = $(MAKE) $(LINUX_PROTO_SHIM_BIN)
endif
WORKLOAD_CLEAN_COMMAND = :
