WORKLOAD_NAME ?= xv6
WORKLOAD_BOARD ?= mycpu_virt

WORKLOADS_DIR := workloads
WORKLOAD_BOARD_PROFILE := $(WORKLOADS_DIR)/boards/$(WORKLOAD_BOARD).mk
WORKLOAD_PROFILE := $(WORKLOADS_DIR)/$(WORKLOAD_NAME)/profile.mk
WORKLOAD_PROBE_SCRIPT := $(WORKLOADS_DIR)/run_debug_cli_probe.py

include $(WORKLOAD_BOARD_PROFILE)
include $(WORKLOAD_PROFILE)
