WORKLOAD_NAME ?= xv6
WORKLOAD_BOARD ?= mycpu_virt

WORKLOADS_DIR := workloads
WORKLOAD_BOARD_PROFILE := $(WORKLOADS_DIR)/boards/$(WORKLOAD_BOARD).mk
WORKLOAD_PROFILE := $(WORKLOADS_DIR)/$(WORKLOAD_NAME)/profile.mk
WORKLOAD_PROBE_SCRIPT := $(WORKLOADS_DIR)/run_debug_cli_probe.py
WORKLOAD_IMAGE_FORMAT ?= elf
WORKLOAD_LOAD_ADDR ?=
WORKLOAD_BOOT_PROTOCOL ?=
WORKLOAD_BOOT_HARTID ?= $(BOARD_BOOT_HARTID)
WORKLOAD_DTB_IMAGE ?=
WORKLOAD_DTB_ADDR ?= $(BOARD_LINUX_DTB_ADDR)
WORKLOAD_INITRD_IMAGE ?=
WORKLOAD_INITRD_ADDR ?= $(BOARD_LINUX_INITRD_ADDR)
WORKLOAD_CMDLINE_IMAGE ?=
WORKLOAD_CMDLINE_ADDR ?= $(BOARD_LINUX_CMDLINE_ADDR)
WORKLOAD_PAYLOAD_ARGS ?=
WORKLOAD_GPR_SEED_ARGS ?=

include $(WORKLOAD_BOARD_PROFILE)
include $(WORKLOAD_PROFILE)

WORKLOAD_AUTO_PAYLOAD_ARGS :=
ifneq ($(strip $(WORKLOAD_DTB_IMAGE)),)
ifneq ($(strip $(WORKLOAD_DTB_ADDR)),)
WORKLOAD_AUTO_PAYLOAD_ARGS += --payload $(WORKLOAD_DTB_IMAGE) $(WORKLOAD_DTB_ADDR)
else
$(error WORKLOAD_DTB_IMAGE requires WORKLOAD_DTB_ADDR)
endif
endif
ifneq ($(strip $(WORKLOAD_INITRD_IMAGE)),)
ifneq ($(strip $(WORKLOAD_INITRD_ADDR)),)
WORKLOAD_AUTO_PAYLOAD_ARGS += --payload $(WORKLOAD_INITRD_IMAGE) $(WORKLOAD_INITRD_ADDR)
else
$(error WORKLOAD_INITRD_IMAGE requires WORKLOAD_INITRD_ADDR)
endif
endif
ifneq ($(strip $(WORKLOAD_CMDLINE_IMAGE)),)
ifneq ($(strip $(WORKLOAD_CMDLINE_ADDR)),)
WORKLOAD_AUTO_PAYLOAD_ARGS += --payload $(WORKLOAD_CMDLINE_IMAGE) $(WORKLOAD_CMDLINE_ADDR)
else
$(error WORKLOAD_CMDLINE_IMAGE requires WORKLOAD_CMDLINE_ADDR)
endif
endif

WORKLOAD_AUTO_GPR_SEED_ARGS :=
ifeq ($(WORKLOAD_BOOT_PROTOCOL),linux)
ifneq ($(strip $(WORKLOAD_BOOT_HARTID)),)
WORKLOAD_AUTO_GPR_SEED_ARGS += --set-reg a0 $(WORKLOAD_BOOT_HARTID)
endif
ifneq ($(strip $(WORKLOAD_DTB_IMAGE)),)
WORKLOAD_AUTO_GPR_SEED_ARGS += --set-reg a1 $(WORKLOAD_DTB_ADDR)
endif
else ifneq ($(strip $(WORKLOAD_BOOT_PROTOCOL)),)
$(error unsupported WORKLOAD_BOOT_PROTOCOL: $(WORKLOAD_BOOT_PROTOCOL))
endif
