XV6_UPSTREAM_COMMIT := 5474d4bf72fd95a6e5c735c2d7f208f58990ceab
XV6_EXTERNAL_DIR := external/xv6-riscv
XV6_KERNEL_ELF := $(XV6_EXTERNAL_DIR)/kernel/kernel
XV6_FS_IMAGE := $(XV6_EXTERNAL_DIR)/fs.img
XV6_TOOLPREFIX ?= riscv64-unknown-elf-
XV6_BUILD_VARS := TOOLPREFIX=$(XV6_TOOLPREFIX) ARCH_MARCH=$(BOARD_XV6_ARCH_MARCH) ARCH_MABI=$(BOARD_XV6_ARCH_MABI) CPUS=$(BOARD_CPU_COUNT)

WORKLOAD_IMAGE := $(XV6_KERNEL_ELF)
WORKLOAD_DISK := $(XV6_FS_IMAGE)
WORKLOAD_PROBE_CYCLES := 4
WORKLOAD_SMOKE_TARGET := test-host-xv6_boot_smoke
WORKLOAD_BUILD_COMMAND = $(MAKE) -C $(XV6_EXTERNAL_DIR) $(XV6_BUILD_VARS) kernel/kernel fs.img
WORKLOAD_CLEAN_COMMAND = $(MAKE) -C $(XV6_EXTERNAL_DIR) clean
